// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmZXvA9GHM3vdZXf-8QagcmH--rtSZUIk',
    appId: '1:587556720172:web:1a608b0d235260a0a78b89',
    messagingSenderId: '587556720172',
    projectId: 'chat-app-94a26',
    authDomain: 'chat-app-94a26.firebaseapp.com',
    storageBucket: 'chat-app-94a26.firebasestorage.app',
    measurementId: 'G-YV5E2BWCX8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA64PzIDM8dM6L5JCS9bU3oAtlE5ktGELU',
    appId: '1:587556720172:android:b650e439929932eaa78b89',
    messagingSenderId: '587556720172',
    projectId: 'chat-app-94a26',
    storageBucket: 'chat-app-94a26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUVkDkMfUV-x5NB6p3SNZTnRh8h7nEbwY',
    appId: '1:587556720172:ios:eaeb215ce1fc9b27a78b89',
    messagingSenderId: '587556720172',
    projectId: 'chat-app-94a26',
    storageBucket: 'chat-app-94a26.firebasestorage.app',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUVkDkMfUV-x5NB6p3SNZTnRh8h7nEbwY',
    appId: '1:587556720172:ios:eaeb215ce1fc9b27a78b89',
    messagingSenderId: '587556720172',
    projectId: 'chat-app-94a26',
    storageBucket: 'chat-app-94a26.firebasestorage.app',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmZXvA9GHM3vdZXf-8QagcmH--rtSZUIk',
    appId: '1:587556720172:web:09d0d85326023d44a78b89',
    messagingSenderId: '587556720172',
    projectId: 'chat-app-94a26',
    authDomain: 'chat-app-94a26.firebaseapp.com',
    storageBucket: 'chat-app-94a26.firebasestorage.app',
    measurementId: 'G-72J1ZZXR7G',
  );
}
